---
- hosts: all
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Run motion-master-bridge container
    docker_container:
      name: motion-master-bridge
      image: synapticon/motion-master-bridge
      network_mode: host
      restart_policy: unless-stopped

  - name: Run oblac-drives container
    docker_container:
      name: oblac-drives
      image: synapticon/oblac-drives
      restart_policy: unless-stopped
      published_ports:
        - 6789:80
      volumes:
        - /opt/oblac-drives/firmwares:/usr/share/nginx/html/firmwares:ro

  - name: Start services
    systemd:
      name: "{{ item }}"
      state: started
    with_items:
      - ethercat.service
      - motion-master.service
