---
- hosts: all
  connection: local
  gather_facts: true
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    bundle_version: ''
    oblac_drives_version: 'latest'
    motion_master_version: ''
    motion_master_bridge_version: 'latest'

  tasks:
  - name: Get oblac-drives port
    shell: docker port oblac-drives | grep 80 | awk '{print $3}' | cut -d ":" -f 2
    register: oblac_drives_docker_container_port
    failed_when: "oblac_drives_docker_container_port.stdout == ''"

  - name: Stop the motion-master-bridge container
    docker_container:
      name: motion-master-bridge
      image: synapticon/motion-master-bridge
      network_mode: host
      restart_policy: unless-stopped
      state: stopped

  - name: Stop the oblac-drives container
    docker_container:
      name: oblac-drives
      image: synapticon/oblac-drives
      restart_policy: unless-stopped
      state: stopped

  - name: Stop ethercat-watchdog.service (if available)
    systemd:
      name: ethercat-watchdog.service
      state: stopped
    ignore_errors: yes

  - name: Stop services
    systemd:
      name: "{{ item }}"
      state: stopped
    with_items:
      - motion-master.service
      - ethercat.service

  - name: Get odb.json from AWS S3 synapticon-tools/firmwares/odb.json
    uri:
      url: https://s3-eu-west-1.amazonaws.com/synapticon-tools/firmwares/odb.json
      method: GET
      return_content: yes
      status_code: 200
      headers:
        Content-Type: application/json
      body_format: json
    register: odb_response

  - name: Copy odb.json to /opt/oblac-drives
    copy:
      content: "{{ odb_response.json }}"
      dest: /opt/oblac-drives/odb.json

  - name: Find bundle in odb.json by bundle_version parameter
    set_fact:
      bundles: "{{ odb_response.json|json_query(\"[?version=='\" + bundle_version + \"']\")}}"

  - debug:
      msg: "{{ bundles[0] }}"
    when: bundles[0] is defined and (bundles[0]|length>0)

  - name: Copy bundle.json to /opt/oblac-drives
    copy:
      content: "{{ bundles[0] }}"
      dest: /opt/oblac-drives/bundle.json
    when: bundles[0] is defined and (bundles[0]|length>0)

  - name: Override oblac_drives_version, motion_master_version and motion_master_bridge_version parameters by dependencies in odb.json
    set_fact:
      oblac_drives_version: "{{ bundles[0].dependencies['oblac-drives'] }}"
      motion_master_version: "{{ bundles[0].dependencies['motion-master'] }}"
      motion_master_bridge_version: "{{ bundles[0].dependencies['motion-master-bridge'] }}"
    when: bundles[0] is defined and (bundles[0]|length>0)

  - name: Create the motion-master-bridge Docker container
    docker_container:
      name: motion-master-bridge
      image: synapticon/motion-master-bridge:{{ motion_master_bridge_version }}
      pull: yes
      recreate: yes
      network_mode: host
      restart_policy: always

  - name: Create the oblac-drives Docker container
    docker_container:
      name: oblac-drives
      image: synapticon/oblac-drives:{{ oblac_drives_version }}
      pull: yes
      recreate: yes
      restart_policy: always
      published_ports:
        - "{{ oblac_drives_docker_container_port.stdout }}:80"
      volumes:
        - /opt/oblac-drives/firmwares:/usr/share/nginx/html/firmwares:ro

  - name: Replace bundle version in the running oblac-drives container
    shell: docker exec oblac-drives sh -c "sed -i -e 's/bundleVersion:\"\"/bundleVersion:\"{{ bundle_version }}\"/' /usr/share/nginx/html/main*.bundle.js"

  - name: Download the latest motion-master binary from AWS S3 synapticon-tools/motion-master/release/
    get_url:
      url: https://s3-eu-west-1.amazonaws.com/synapticon-tools/motion-master/release/motion-master
      dest: /opt/oblac-drives/motion-master
      mode: 0755
      force: yes
    when: motion_master_version == ''

  - name: Download motion-master binary from AWS S3 synapticon-tools/motion-master/release/
    get_url:
      url: https://s3-eu-west-1.amazonaws.com/synapticon-tools/motion-master/release/motion-master-{{ motion_master_version }}
      dest: /opt/oblac-drives/motion-master
      mode: 0755
      force: yes
    when: motion_master_version != ''

  - name: Reboot
    command: /sbin/reboot
