---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: EC2 Facts
      ec2_instance_facts:
        filters:
          "tag:Name": ubuntu-16.04.3-server-amd64
      register: ec2

    - name: Terminate EC2 instances
      ec2:
        region: us-east-1
        instance_ids: "{{ item.instance_id }}"
        state: absent
      with_items: "{{ ec2.instances }}"

    - name: Launch EC2 instance
      ec2:
        region: us-east-1
        group_id: sg-15931962
        instance_type: t2.micro
        image: ami-383c3442
        vpc_subnet_id: subnet-adcbe497
        wait: yes
        count: 1
        assign_public_ip: yes
        volumes:
          - device_name: /dev/sda1
            volume_size: 20
            delete_on_termination: true
        instance_tags:
          Name: ubuntu-16.04.3-server-amd64
      register: ec2

    - name: Store EC2 instance fact
      set_fact:
        ec2_instance: "{{ ec2.instances | first }}"
      when: ec2.changed

    - name: Wait for SSH service
      wait_for:
        host: "{{ ec2_instance.public_ip }}"
        port: 22

    - name: Add EC2 IP to host group
      add_host: hostname={{ ec2_instance.public_ip }} group=ec2_hosts

- hosts: ec2_hosts
  user: ubuntu
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ubuntu
    ansible_ssh_pass: ubuntu
    ansible_become: true
    ansible_sudo_pass: ubuntu
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

  roles:
    - oblac-drives
