---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: EC2 Facts
      ec2_instance_facts:
        region: us-east-1
        filters:
          "tag:Name": ubuntu-16.04.3-server-amd64
      register: ec2

    - name: Terminate EC2 instances
      ec2:
        region: us-east-1
        instance_ids: "{{ item.instance_id }}"
        state: absent
      with_items: "{{ ec2.instances }}"

    - name: Launch EC2 instance
      ec2:
        region: us-east-1
        group_id: sg-15931962
        instance_type: t2.micro
        image: ami-383c3442
        vpc_subnet_id: subnet-adcbe497
        wait: yes
        count: 1
        assign_public_ip: no
        volumes:
          - device_name: /dev/sda1
            volume_size: 20
            delete_on_termination: true
        instance_tags:
          Name: ubuntu-16.04.3-server-amd64
      register: ec2

    - name: Store EC2 instance fact
      set_fact:
        ec2_instance: "{{ ec2.instances | first }}"
      when: ec2.changed

    - name: Wait for SSH service
      wait_for:
        host: "{{ ec2_instance.private_ip }}"
        port: 22

    - name: Add EC2 IP to host group
      add_host: hostname={{ ec2_instance.private_ip }} group=ec2_hosts

    - name: Sync firmwares
      command: aws s3 sync s3://synapticon-tools/firmwares firmwares

- hosts: ec2_hosts
  user: ubuntu
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ubuntu
    ansible_ssh_pass: ubuntu
    ansible_become: true
    ansible_sudo_pass: ubuntu
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    bundle_version: ''
    oblac_drives_version: 'latest'
    motion_master_version: 'latest'
    motion_master_bridge_version: 'latest'

  tasks:

   - name: Copy firmwares
     copy:
       src: firmwares
       dest: /opt

  roles:
    - oblac-drives

- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Export EC2 instance
      command: aws ec2 create-instance-export-task --description "Ubuntu Server 16.04.3 LTS" --instance-id {{ hostvars["localhost"]["ec2_instance"]["id"] }} --target-environment vmware --export-to-s3-task DiskImageFormat=VMDK,ContainerFormat=ova,S3Bucket=oblac-drives
      register: export_task

    - debug: msg="{{ export_task.stdout }}"
    - debug: msg="{{ export_task.stderr }}"
