---
- hosts: all
  connection: local
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    bundle_version: ''
    oblac_drives_version: 'latest'
    motion_master_version: ''
    motion_master_bridge_version: 'latest'
    ethercat_interface: 'eth0'
    native: true

  pre_tasks:

  - name: Remove cdrom sources from /etc/apt/sources.list
    lineinfile:
      path: /etc/apt/sources.list
      regexp: '^deb cdrom'
      state: absent

  roles:
    - build-packages
    - ethercat-master
    - odb
    - docker
    - motion-master-bridge
    - oblac-drives
    - motion-master
    - util
