---
- hosts: vm
  tasks:
    - name: Set synapticon as host name for loopback interface
      lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: '127.0.1.1	synapticon'
    - name: Replace /etc/hostname
      copy:
        src: ./root/etc/hostname
        dest: /etc/hostname
        owner: root
        group: root
        mode: 0644

    - name: Run sudo command with no password for ubuntu user
      lineinfile:
        path: /etc/sudoers
        line: 'ubuntu ALL=(ALL) NOPASSWD:ALL'

    - name: Change grub screen resolution
      lineinfile:
        path: /etc/default/grub
        regexp: '^#GRUB_GFXMODE=640x480'
        line: 'GRUB_GFXMODE=1024x768'
    - name: Update grub
      command: /usr/sbin/update-grub

    - name: Remove cdrom sources from /etc/apt/sources.list
      lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb cdrom'
        state: absent

    - name: Install build packages
      apt: name={{item}} update_cache=yes
      with_items:
        - build-essential
        - autoconf
        - libtool
        - git
        - python3-pip

    - name: Install packages to allow apt to use a repository over HTTPS
      apt: name={{item}} update_cache=yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
    - name: Add Docker official GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    - name: Install Docker CE
      apt: name=docker-ce
    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
    - name: Pip install docker-py
      pip: name=docker-py
    - name: Run motion-master-bridge container
      docker_container:
        name: motion-master-bridge
        image: synapticon/motion-master-bridge
        recreate: yes
        network_mode: host
        restart_policy: always
    - name: Run oblac-drives container
      docker_container:
        name: oblac-drives
        image: synapticon/oblac-drives
        recreate: yes
        restart_policy: always
        published_ports:
          - 80:80
    
    - name: Git clone Etherlab_EtherCAT_Master
      git:
        repo: https://github.com/synapticon/Etherlab_EtherCAT_Master.git
        dest: /opt/Etherlab_EtherCAT_Master
    - name: Install Etherlab_EtherCAT_Master
      command: "{{ item }}"
      with_items:
        - "./bootstrap"
        - "./configure --enable-sii-assign --disable-8139too --enable-hrtimer --enable-cycles"
        - "make all modules"
        - "make modules_install install"
        - "ldconfig"
        - "depmod"
      args:
        chdir: /opt/Etherlab_EtherCAT_Master
    - name: Remove cloned Etherlab_EtherCAT_Master directory
      file:
        state: absent
        path: /opt/Etherlab_EtherCAT_Master
    - name: Add ethercat binary to $PATH
      file:
        src: /opt/etherlab/bin/ethercat
        dest: /usr/local/bin/ethercat
        state: link
