---
- hosts: all
  connection: local
  gather_facts: true
  become: yes

  vars:
    target: 'up2'
    ansible_python_interpreter: /usr/bin/python3
    oblac_drives_version: 'latest'
    motion_master_version: ''
    motion_master_bridge_version: 'latest'
    ethercat_interface: 'enp3s0'
    required_docker_version: '17.05.0'

  vars_prompt:
  - name: "bundle_version"
    prompt: "\e[1;33mEnter the bundle version to install or leave empty for the latest version.\e[0m"
    default: ""
    private: no

  - name: "oblac_drives_port"
    prompt: "\e[1;33mEnter the port number to bind OBLAC Drives to.\e[0m"
    default: "80"
    private: no

  pre_tasks:
  - name: Remove cdrom sources from /etc/apt/sources.list
    lineinfile:
      path: /etc/apt/sources.list
      regexp: '^deb cdrom'
      state: absent

  - name: Create the oblac-drives directory
    file:
      path: /opt/oblac-drives
      state: directory

  roles:
    - role: dependencies
      tags: dependencies
    - role: util
      tags: util
    - role: ethercat-master
      tags: ethercat-master
    - role: odb
      tags: odb
    - role: docker
      tags: docker
    - role: motion-master-bridge
      tags: motion-master-bridge
    - role: oblac-drives
      tags: oblac-drives
    - role: motion-master
      tags: motion-master
    - role: up2
      tags: up2
    - role: oblac-drives-ip-addr
      tags: oblac-drives-ip-addr
