---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

  - name: Sync firmwares
    command: aws s3 sync s3://synapticon-tools/firmwares firmwares

- hosts: vm
  user: ubuntu
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ubuntu
    ansible_ssh_pass: ubuntu
    ansible_become: true
    ansible_sudo_pass: ubuntu
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    bundle_version: ''
    oblac_drives_version: 'latest'
    motion_master_version: ''
    motion_master_bridge_version: 'latest'
    ethercat_interface: 'ens33'
    required_docker_version: '17.05.0'

  pre_tasks:

  - name: Remove cdrom sources from /etc/apt/sources.list
    lineinfile:
      path: /etc/apt/sources.list
      regexp: '^deb cdrom'
      state: absent

  - name: set timezone to UTC
    timezone:
      name: Etc/UTC

  - name: Create the oblac-drives directory
    file:
      path: /opt/oblac-drives
      state: directory

  - name: Copy firmwares
    copy:
      src: firmwares
      dest: /opt/oblac-drives

  roles:
    - ubuntu-user
    - network
    - grub
    - dependencies
    - ethercat-master-sncn-installer
    - odb
    - docker
    - motion-master-bridge
    - oblac-drives
    - motion-master
    - services
    - util
    - ansible
    - clean-up
