---
- name: Install build packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - build-essential
    - autoconf
    - libtool
    - git
    - python3-pip
    - python-jmespath
