---
- name: Create the oblac-drives Docker container
  docker_container:
    name: oblac-drives
    image: synapticon/oblac-drives:{{ oblac_drives_version }}
    pull: yes
    recreate: yes
    restart_policy: always
    published_ports:
      - {{ oblac_drives_port }}:80
    volumes:
      - /opt/oblac-drives/firmwares:/usr/share/nginx/html/firmwares:ro

- name: Replace bundle version in the running oblac-drives container
  shell: docker exec oblac-drives sh -c "sed -i -e 's/bundleVersion:\"\"/bundleVersion:\"{{ bundle_version }}\"/' /usr/share/nginx/html/main*.bundle.js"
