---
- stat:
    path: /bin/ethercat 
  register: ethercat

- stat:
    path: /opt/etherlab 
  register: etherlab

- name: Git clone Etherlab_EtherCAT_Master
  git:
    repo: https://github.com/synapticon/Etherlab_EtherCAT_Master.git
    dest: /opt/Etherlab_EtherCAT_Master
    version: develop
  when:
    - not ethercat.stat.exists
    - not etherlab.stat.exists

- name: Install Etherlab_EtherCAT_Master
  command: ./install.sh {{ ethercat_interface }}
  args:
    chdir: /opt/Etherlab_EtherCAT_Master/sncn_installer
  when:
    - not ethercat.stat.exists
    - not etherlab.stat.exists

- name: Remove cloned Etherlab_EtherCAT_Master directory
  file:
    state: absent
    path: /opt/Etherlab_EtherCAT_Master
  when:
    - not ethercat.stat.exists
    - not etherlab.stat.exists

- name: Copy the ethercat.service systemd file
  copy:
    src: etc/systemd/system/ethercat.service
    dest: /etc/systemd/system/
    owner: root
    mode: 0644
    force: no

- name: Enable EtherCAT systemd service
  systemd:
    name: ethercat.service
    enabled: yes

- name: Start ethercat.service after installation, but disable automatic start on boot
  systemd:
    name: ethercat.service
    enabled: no
    state: started
  when:
    - native is defined
    - native