---
- name: Copy 00-header motd file
  copy:
    src: etc/update-motd.d/00-header
    dest: /etc/update-motd.d/00-header
    owner: root
    mode: 0755

- name: Copy 10-help-text motd file
  template:
    src: etc/update-motd.d/10-help-text.j2
    dest: /etc/update-motd.d/10-help-text
    owner: root
    mode: 0755