---
- hosts: all
  connection: ssh
  gather_facts: true

  vars:
    ansible_user: drive
    ansible_ssh_pass: drive
    ansible_become: true
    ansible_become_pass: drive
    box_user: drive
    box_docker_engine_api_port: 62376
    docker_users:
      - '{{ box_user }}'
    pip_install_packages:
      - name: docker

  pre_tasks:
  - name: Remove cdrom sources from /etc/apt/sources.list
    lineinfile:
      path: /etc/apt/sources.list
      regexp: '^deb cdrom'
      state: absent
  - name: Set timezone to UTC
    timezone:
      name: Etc/UTC

  roles:
    - common
    - grub
    - box-user
    - network
    - geerlingguy.pip
    - geerlingguy.docker
    - igh-ethercat-master
    - { role: oblac-drives-update-service, tags: ['odus'] }
    - { role: up2, when: box_target == 'up2', tags: ['up2'] }
