---
- hosts: all
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3
    bundle_version: ''
    oblac_drives_version: 'latest'
    motion_master_bridge_version: 'latest'

  tasks:
  - name: Get bundle information from the bundle.json file
    set_fact:
      bundle_version: "{{ lookup('file', 'bundle.json') | from_json }}"
    ignore_errors: yes

  - debug:
      msg: "{{ bundle_version }}"
    when:
      - bundle_version is defined
      - bundle_version != ""

  - name: Override oblac_drives_version and motion_master_version parameters by dependencies in bundle.json
    set_fact:
      oblac_drives_version: "{{ bundle_version.dependencies['oblac-drives'] }}"
      motion_master_bridge_version: "{{ bundle_version.dependencies['motion-master-bridge'] }}"
    when:
      - bundle_version is defined
      - bundle_version != ""

  - name: Run motion-master-bridge container
    docker_container:
      name: motion-master-bridge
      image: synapticon/motion-master-bridge:{{ motion_master_bridge_version }}
      network_mode: host
      restart_policy: unless-stopped

  - name: Run oblac-drives container
    docker_container:
      name: oblac-drives
      image: synapticon/oblac-drives:{{ oblac_drives_version }}
      restart_policy: unless-stopped
      published_ports:
        - 80:80
      volumes:
        - /opt/oblac-drives/firmwares:/usr/share/nginx/html/firmwares:ro

  - name: Start services
    systemd:
      name: "{{ item }}"
      state: started
    with_items:
      - ethercat.service
      - motion-master.service
