---
- name: Set authorized key for SSH access
  authorized_key:
    user: '{{ box_user }}'
    key: '{{ item }}'
    state: present
    exclusive: True
  with_file:
    - rsa.pub

- name: Ensures /etc/systemd/system/getty@tty1.service.d dir exists
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory

- name: 'Enable autologin for {{ box_user }} user'
  template:
    src: etc/systemd/system/getty@tty1.service.d/override.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
