---
# https://wiki.debian.org/iwlwifi
- name: Add a "non-free" repo
  apt_repository:
    repo: deb http://httpredir.debian.org/debian/ stretch main contrib non-free
    state: present
    update_cache: yes

- name: Install network related packages
  apt:
    name: '{{ item }}'
    update_cache: yes
  with_items:
    - firmware-iwlwifi
    - wpasupplicant
    - isc-dhcp-server
    - ufw

- name: Add the iwlwifi module
  modprobe:
    name: iwlwifi
    state: present

- include: wifi.yml
- include: ssh.yml
