---
- stat: path=/opt/etherlab
  register: etherlab

- name: Git clone Etherlab_EtherCAT_Master
  git:
    repo: https://github.com/synapticon/Etherlab_EtherCAT_Master.git
    dest: /opt/Etherlab_EtherCAT_Master
    version: develop
  when: etherlab.stat.exists == False

- name: Install Etherlab_EtherCAT_Master
  command: ./install.sh {{ ethercat_interface }}
  args:
    chdir: /opt/Etherlab_EtherCAT_Master/sncn_installer
  when: etherlab.stat.exists == False

- name: Remove cloned Etherlab_EtherCAT_Master directory
  file:
    state: absent
    path: /opt/Etherlab_EtherCAT_Master
  when: etherlab.stat.exists == False

