---
- name: Run motion-master-bridge container
  docker_container:
    name: motion-master-bridge
    image: synapticon/motion-master-bridge:{{ motion_master_bridge_version }}
    pull: yes
    recreate: yes
    network_mode: host
    restart_policy: always
