---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - build-essential
    - autoconf
    - libtool
    - git
    - python3-pip

- name: Install/update the open-vm-tools
  apt:
    name: open-vm-tools
    update_cache: yes
    state: latest
