---
- name: Copy systemd services
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    owner: root
    mode: 0644
  with_fileglob:
    - etc/systemd/system/*.service

- name: Start services after installation, but disable automatic start on boot
  systemd:
    name: "{{ item }}"
    enabled: no
    state: started
  with_items:
    - ethercat.service
    - motion-master.service
