---
- name: Copy the ethercat.service systemd file
  copy:
    src: etc/systemd/system/ethercat.service
    dest: /etc/systemd/system/
    owner: root
    mode: 0644
    force: no

- name: Copy the motion-master.service systemd file
  copy:
    src: etc/systemd/system/motion-master.service
    dest: /etc/systemd/system/
    owner: root
    mode: 0644

- name: Copy the ethercat-update-conf.service systemd file
  copy:
    src: etc/systemd/system/ethercat-update-conf.service
    dest: /etc/systemd/system/
    owner: root
    mode: 0644
  when: native is not defined

- name: Copy the ethercat-watchdog.service systemd file
  copy:
    src: etc/systemd/system/ethercat-watchdog.service
    dest: /etc/systemd/system/
    owner: root
    mode: 0644
  when: native is not defined

- name: Enable systemd services
  systemd:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - ethercat-update-conf.service
    - ethercat.service
    - ethercat-watchdog.service
    - motion-master.service
  when: native is not defined

- name: Start services after installation, but disable automatic start on boot
  systemd:
    name: "{{ item }}"
    enabled: no
    state: started
  with_items:
    - ethercat.service
    - motion-master.service
  when:
    - native is defined
    - native
