---
- name: Run sudo command with no password for ubuntu user
  lineinfile:
    path: /etc/sudoers
    line: 'ubuntu ALL=(ALL) NOPASSWD:ALL'

- name: Change the default ubuntu user password to nRMn52qGPXkAKBxNliJ8
  user:
    name: 'ubuntu'
    password: '$6$bjwZcCrvQ10Qu$yF64e32jkUub.oUyz9deO6NMMc5ayJoGan5UQ5hgh9aOtDg84lxk.MaQCpuyoMHyXyyAkTue1.p9pduedQpBT1'

- name: Set authorized key
  authorized_key:
    user: ubuntu
    key: "{{ item }}"
    state: present
    exclusive: True
  with_file:
    - rsa.pub

- name: Enable autologin for ubuntu user
  copy:
    src: etc/systemd/system/getty@tty1.service.d
    dest: /etc/systemd/system/
